before_script:
    - module load gfortran/6.2
    - module load anaconda3/2019-03

stages:
    - build
    - test
    - deploy

build1:
    stage: build
    script:
        - python pre_odevec.py --nvector=32 --example="PRIMORDIAL"
        - cd build
        - gfortran -O2 -c -g -cpp -DHAVE_COEFFICIENTS -fcheck=all -fno-range-check -Wall -fbacktrace odevec.f90 odevec_commons.f90 test.f90
        - gfortran -O2 -o primordial *.o
    artifacts:
        expire_in: 4 weeks
        paths:
        - build/primordial
    only:
        - master

test1:
    stage: test
    script:
        - ./build/primordial
    only:
        - master
